### ISSUE TITLE
Issues with certain dependency ports on Leopard

### ISSUE THREAD

**Issue by strangeexperiences** [macos-powerpc/powerpc-ports#45]
[logs.zip](https://github.com/user-attachments/files/24358888/logs.zip)

I have attached the logs for vim, QMPlay2, py313-asn1, gd2, libb64 (which I initially forgot about in my forum post) and ghostscript.

I will attach logs of yt-dlp and yt-dlp-ejs in the future, in case issues still persist after fixing gd2

**Comment by barracuda156** [comment]
@strangeexperiences Thank you, this is helpful.

`gd2`: same issue as https://trac.macports.org/ticket/73143
Try adding `compiler.cxx_standard 2011` into `gd2`portfile, it should fix it (I dunno if it uses C++, but the effect will be correct anyway).

`QMPlay2`: something possibly got messed with portgroup vs portfile. I will address that. The issue should not be specific to 10.5 or powerpc.

`py313-asn1`, `ghostscript` and `libb64`: please try disabling HFS compression in `/opt/local/etc/macports/macports.conf`, so that it has `hfscompression no`, uncommented. Clean the port (`sudo port clean --all py313-asn1`), try again.

`vim`: looks like it is broken on 10.5, I will see what can be done.

**Comment by barracuda156** [comment]
`QMPlay2` issue is essentially this: https://github.com/RJVB/macstrop/issues/110#issue-2460622542
Now we just need to figure out how to fix it reliably, since currently it seems to happen in some cases but not other.

**Comment by strangeexperiences** [comment]
So far so good, py313-asn1, ghostscript, libb64 and gd2 are successful. yt-dlp and yt-dlp-ejs started to install successfully using python313 as well, which progresses me to QMPlay2 - which however, still fails with path change in CMakeLists.txt

[main_qmplay2.log](https://github.com/user-attachments/files/24359909/main_qmplay2.log)

**Comment by barracuda156** [comment]
Could you attach output of `port contents qt4-mac`?

**Comment by barracuda156** [comment]
> Update: still stuck on destroot, there were no lines after target build, and deleting the folder didn’t help

You could delete both build and configure targets, let it reconfigure.
As you can see from your output, the file exists: `/opt/local/libexec/qt4/share/plugins/iconengines/libqsvgicon.dylib`.

P. S. After all, it may be faster to just rebuild. Edit this line https://github.com/macos-powerpc/powerpc-ports/blob/a0e30c0879f703fb339945b21d06f7704cd69998/multimedia/QMPlay2/Portfile#L245 in portfile, replacing `${qt_plugins_dir}` with `/opt/local/libexec/qt4/share/plugins`.

**Comment by barracuda156** [comment]
Fix for `vim`: https://github.com/macos-powerpc/powerpc-ports/commit/c96b1184e2a1f2d3b3f2eeab3163484b525401c9
